### ISSUE TITLE
The binary supplied is newer version than source code

### ISSUE THREAD

**Issue by MarkWhybird** [rocketinventor/web-page-screensaver#14]
Looks like the binary at  https://github.com/rocketinventor/web-page-screensaver/raw/master/Web-Page-Screensaver.scr is a newer, better version than the source code here on github makes; it has a better preferences window, for example. Did the wrong version of the code come over from google?

**Comment by MarkWhybird** [comment]
Hm - I just realised that https://github.com/cwc/web-page-screensaver is not the same github project as this one. That is where the newer source code is.

**Comment by rocketinventor** [comment]
@MarkWhybird Yes, that is indeed newer.
I only cloned the old Google repository in case it got taken down, without the intent of maintaining it.
I'm going to link to that repository, now.

**Comment by MarkWhybird** [comment]
Awesome - thanks.
